
export const categories = [
    {
        name: 'Quantity Estimator',
        slug: 'quantity-estimator',
        icon: 'fa-calculator',
        theme: 'green',
        count: 27,
        description: 'Estimate materials for construction.'
    },
    {
        name: 'Concrete Technology',
        slug: 'concrete-technology',
        icon: 'fa-cubes',
        theme: 'gray',
        count: 6,
        description: 'Concrete mix and testing.'
    },
    {
        name: 'Road Construction',
        slug: 'road-construction',
        icon: 'fa-road',
        theme: 'zinc',
        count: 2,
        description: 'Bitumen and road layers.'
    },
    {
        name: 'Soil Test',
        slug: 'soil-test',
        icon: 'fa-vial',
        theme: 'amber',
        count: 12,
        description: 'Geotechnical engineering tests.'
    },
    {
        name: 'Sieve Analysis',
        slug: 'sieve-analysis-aggregates',
        icon: 'fa-filter',
        theme: 'blue',
        count: 31,
        description: 'Gradation of aggregates.'
    },
    {
        name: 'Blending of Aggregates',
        slug: 'blending-aggregates',
        icon: 'fa-blender',
        theme: 'purple',
        count: 31,
        description: 'Mixing proportions.'
    },
    {
        name: 'Environmental Eng.',
        slug: 'environmental-engineering',
        icon: 'fa-leaf',
        theme: 'emerald', // Distinct from Quantity Green
        count: 3,
        description: 'Water and waste management.'
    },
    {
        name: 'Steel Design',
        slug: 'steel-design',
        icon: 'fa-drafting-compass',
        theme: 'indigo',
        count: 2,
        description: 'Structural steel calculations.'
    },
    {
        name: 'Foundation',
        slug: 'foundation',
        icon: 'fa-layer-group',
        theme: 'stone',
        count: 2,
        description: 'Footing and pile design.'
    },
    {
        name: 'Health',
        slug: 'health',
        icon: 'fa-heartbeat',
        theme: 'rose',
        count: 5,
        description: 'BMI and health metrics.'
    },
    {
        name: 'Math',
        slug: 'math',
        icon: 'fa-square-root-alt',
        theme: 'teal',
        count: 5,
        description: 'Mathematical calculations.'
    }
];

// Helper to get color classes based on theme
export const getThemeClasses = (theme) => {
    const themes = {
        green: {
            text: 'text-green-600',
            bg: 'bg-green-600',
            bgLight: 'bg-green-50',
            bsSoft: 'bg-green-100', // for charts/light bgs
            border: 'border-green-200',
            hover: 'hover:bg-green-700',
            focus: 'focus:border-green-600',
            gradient: 'from-green-500 to-emerald-600',
            shadow: 'shadow-green-200',
            button: 'bg-green-600 hover:bg-green-700 text-white',
            accent: 'text-green-600',
        },
        blue: {
            text: 'text-blue-600',
            bg: 'bg-blue-600',
            bgLight: 'bg-blue-50',
            bsSoft: 'bg-blue-100',
            border: 'border-blue-200',
            hover: 'hover:bg-blue-700',
            focus: 'focus:border-blue-600',
            gradient: 'from-blue-500 to-indigo-600',
            shadow: 'shadow-blue-200',
            button: 'bg-blue-600 hover:bg-blue-700 text-white',
            accent: 'text-blue-600',
        },
        indigo: {
            text: 'text-indigo-600',
            bg: 'bg-indigo-600',
            bgLight: 'bg-indigo-50',
            bsSoft: 'bg-indigo-100',
            border: 'border-indigo-200',
            hover: 'hover:bg-indigo-700',
            focus: 'focus:border-indigo-600',
            gradient: 'from-indigo-500 to-purple-600',
            shadow: 'shadow-indigo-200',
            button: 'bg-indigo-600 hover:bg-indigo-700 text-white',
            accent: 'text-indigo-600',
        },
        purple: {
            text: 'text-purple-600',
            bg: 'bg-purple-600',
            bgLight: 'bg-purple-50',
            bsSoft: 'bg-purple-100',
            border: 'border-purple-200',
            hover: 'hover:bg-purple-700',
            focus: 'focus:border-purple-600',
            gradient: 'from-purple-500 to-fuchsia-600',
            shadow: 'shadow-purple-200',
            button: 'bg-purple-600 hover:bg-purple-700 text-white',
            accent: 'text-purple-600',
        },
        amber: {
            text: 'text-amber-600',
            bg: 'bg-amber-600',
            bgLight: 'bg-amber-50',
            bsSoft: 'bg-amber-100',
            border: 'border-amber-200',
            hover: 'hover:bg-amber-700',
            focus: 'focus:border-amber-600',
            gradient: 'from-amber-500 to-orange-600',
            shadow: 'shadow-amber-200',
            button: 'bg-amber-600 hover:bg-amber-700 text-white',
            accent: 'text-amber-600',
        },
        orange: {
            text: 'text-orange-600',
            bg: 'bg-orange-600',
            bgLight: 'bg-orange-50',
            bsSoft: 'bg-orange-100',
            border: 'border-orange-200',
            hover: 'hover:bg-orange-700',
            focus: 'focus:border-orange-600',
            gradient: 'from-orange-500 to-red-600',
            shadow: 'shadow-orange-200',
            button: 'bg-orange-600 hover:bg-orange-700 text-white',
            accent: 'text-orange-600',
        },
        gray: {
            text: 'text-gray-600',
            bg: 'bg-gray-600',
            bgLight: 'bg-gray-50',
            bsSoft: 'bg-gray-100',
            border: 'border-gray-200',
            hover: 'hover:bg-gray-700',
            focus: 'focus:border-gray-600',
            gradient: 'from-gray-500 to-slate-600',
            shadow: 'shadow-gray-200',
            button: 'bg-gray-600 hover:bg-gray-700 text-white',
            accent: 'text-gray-600',
        },
        zinc: {
            text: 'text-zinc-600',
            bg: 'bg-zinc-600',
            bgLight: 'bg-zinc-50',
            bsSoft: 'bg-zinc-100',
            border: 'border-zinc-200',
            hover: 'hover:bg-zinc-700',
            focus: 'focus:border-zinc-600',
            gradient: 'from-zinc-500 to-neutral-600',
            shadow: 'shadow-zinc-200',
            button: 'bg-zinc-600 hover:bg-zinc-700 text-white',
            accent: 'text-zinc-600',
        },
        stone: {
            text: 'text-stone-600',
            bg: 'bg-stone-600',
            bgLight: 'bg-stone-50',
            bsSoft: 'bg-stone-100',
            border: 'border-stone-200',
            hover: 'hover:bg-stone-700',
            focus: 'focus:border-stone-600',
            gradient: 'from-stone-500 to-neutral-600',
            shadow: 'shadow-stone-200',
            button: 'bg-stone-600 hover:bg-stone-700 text-white',
            accent: 'text-stone-600',
        },
        emerald: {
            text: 'text-emerald-600',
            bg: 'bg-emerald-600',
            bgLight: 'bg-emerald-50',
            bsSoft: 'bg-emerald-100',
            border: 'border-emerald-200',
            hover: 'hover:bg-emerald-700',
            focus: 'focus:border-emerald-600',
            gradient: 'from-emerald-500 to-teal-600',
            shadow: 'shadow-emerald-200',
            button: 'bg-emerald-600 hover:bg-emerald-700 text-white',
            accent: 'text-emerald-600',
        },
        yellow: {
            text: 'text-yellow-600',
            bg: 'bg-yellow-600',
            bgLight: 'bg-yellow-50',
            bsSoft: 'bg-yellow-100',
            border: 'border-yellow-200',
            hover: 'hover:bg-yellow-700',
            focus: 'focus:border-yellow-600',
            gradient: 'from-yellow-500 to-orange-600',
            shadow: 'shadow-yellow-200',
            button: 'bg-yellow-600 hover:bg-yellow-700 text-white',
            accent: 'text-yellow-600',
        },
        rose: {
            text: 'text-rose-600',
            bg: 'bg-rose-600',
            bgLight: 'bg-rose-50',
            bsSoft: 'bg-rose-100',
            border: 'border-rose-200',
            hover: 'hover:bg-rose-700',
            focus: 'focus:border-rose-600',
            gradient: 'from-rose-500 to-pink-600',
            shadow: 'shadow-rose-200',
            button: 'bg-rose-600 hover:bg-rose-700 text-white',
            accent: 'text-rose-600',
        },
        teal: {
            text: 'text-teal-600',
            bg: 'bg-teal-600',
            bgLight: 'bg-teal-50',
            bsSoft: 'bg-teal-100',
            border: 'border-teal-200',
            hover: 'hover:bg-teal-700',
            focus: 'focus:border-teal-600',
            gradient: 'from-teal-500 to-cyan-600',
            shadow: 'shadow-teal-200',
            button: 'bg-teal-600 hover:bg-teal-700 text-white',
            accent: 'text-teal-600',
        },
    };

    return themes[theme] || themes.blue; // Default to Blue
};
